So you want that, be your customer to keep your keep the account in your bank active for a long time.

This will not leave your bank and join another bank so you can predict whether any customer is going

The customer will leave the bank or not

Churn => when a client cancel a subscription
Base on consumptions, if the customer will cancel the service
Detect customer with high risk of leaving

In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import files
files.upload()

{}

In [ ]:
dataset = pd.read_csv("Churn_Modelling.csv")
dataset.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [ ]:
X = dataset.iloc[:,3:-1]
y = dataset.iloc[:,-1].values

In [ ]:
X.head()

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [ ]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [ ]:
print(X["Geography"].value_counts())
print(X["Gender"].value_counts())
print(X["NumOfProducts"].value_counts())
print(X["HasCrCard"].value_counts())
print(X["IsActiveMember"].value_counts())

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64
Male      5457
Female    4543
Name: Gender, dtype: int64
1    5084
2    4590
3     266
4      60
Name: NumOfProducts, dtype: int64
1    7055
0    2945
Name: HasCrCard, dtype: int64
1    5151
0    4849
Name: IsActiveMember, dtype: int64

In [ ]:
X.describe()

        CreditScore           Age  ...  IsActiveMember  EstimatedSalary
count  10000.000000  10000.000000  ...    10000.000000     10000.000000
mean     650.528800     38.921800  ...        0.515100    100090.239881
std       96.653299     10.487806  ...        0.499797     57510.492818
min      350.000000     18.000000  ...        0.000000        11.580000
25%      584.000000     32.000000  ...        0.000000     51002.110000
50%      652.000000     37.000000  ...        1.000000    100193.915000
75%      718.000000     44.000000  ...        1.000000    149388.247500
max      850.000000     92.000000  ...        1.000000    199992.480000

[8 rows x 8 columns]

In [ ]:
X.columns

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary'],
      dtype='object')

In [ ]:
X.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
dtype: int64

In [ ]:
X.dtypes

CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
dtype: object

In [ ]:
unique,counts = np.unique(y,return_counts=True)
np.asarray((unique,counts))

array([[   0,    1],
       [7963, 2037]])

In [ ]:
X=pd.get_dummies(X,drop_first=True) # here we convert data to numeric
X.head()

   CreditScore  Age  Tenure  ...  Geography_Germany  Geography_Spain  Gender_Male
0          619   42       2  ...                  0                0            0
1          608   41       1  ...                  0                1            0
2          502   42       8  ...                  0                0            0
3          699   39       1  ...                  0                0            0
4          850   43       2  ...                  0                1            0

[5 rows x 11 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.15,stratify=y,random_state=0)
#This stratify parameter makes a split so that the proportion of values in the sample produced will be the same
#  as the proportion of values provided to parameter stratify.

#For example, if variable y is a binary categorical variable with values 0 and 1 and 
#there are 25% of zeros and 75% of ones, stratify=y will make sure that your random split has 25% of 0's and 75% of 1's.

In [ ]:
X_train

      CreditScore  Age  Tenure  ...  Geography_Germany  Geography_Spain  Gender_Male
5823          751   51       7  ...                  1                0            0
2217          666   35       2  ...                  0                1            1
6423          652   41       8  ...                  0                1            1
5783          624   71       7  ...                  0                0            1
937           850   44       5  ...                  1                0            0
...           ...  ...     ...  ...                ...              ...          ...
2795          515   25       7  ...                  0                0            0
1733          614   32       7  ...                  1                0            1
4674          850   41       1  ...                  1                0            1
6633          729   42       7  ...                  0                1            0
8389          743   25       6  ...                  0                1            1

[8500 rows x 11 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[ 1.03682098  1.15867808  0.69679344 ...  1.72232466 -0.57191626
  -1.09379268]
 [ 0.15827867 -0.37159838 -1.0351044  ... -0.58061063  1.74850772
   0.91425004]
 [ 0.01357758  0.20225529  1.043173   ... -0.58061063  1.74850772
   0.91425004]
 ...
 [ 2.06006438  0.20225529 -1.38148396 ...  1.72232466 -0.57191626
   0.91425004]
 [ 0.80943356  0.29789757  0.69679344 ... -0.58061063  1.74850772
  -1.09379268]
 [ 0.95413465 -1.32802118  0.35041387 ... -0.58061063  1.74850772
   0.91425004]]

In [ ]:
print(X_test)

[[ 2.06006438 -0.94545206  0.35041387 ... -0.58061063 -0.57191626
   0.91425004]
 [-1.18537428  0.10661301  1.38955257 ... -0.58061063  1.74850772
   0.91425004]
 [ 2.06006438 -1.90187485  1.043173   ... -0.58061063 -0.57191626
   0.91425004]
 ...
 [-1.17503849 -0.08467155 -1.38148396 ... -0.58061063  1.74850772
  -1.09379268]
 [ 0.57171035  0.68046669 -1.0351044  ... -0.58061063  1.74850772
  -1.09379268]
 [ 0.65439668  0.58482441  1.38955257 ...  1.72232466 -0.57191626
  -1.09379268]]

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred = rf.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))

[[1157   37]
 [ 172  134]]
0.8606666666666667

In [ ]:
import pickle
pickle.dump(rf,open("Customer_Churn_Prediction.pkl","wb"))

In [ ]:
# try different preprocessing techniques
# train model with more data
# try different ML algos